# Generated by Django 6.1.1 on 2026-10-06 19:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesaOcupacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('responsavel', models.CharField(blank=True, default='Consumidor Final', max_length=255)),
                ('data_abertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada')], default='ABERTA', max_length=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocupacoes', to='restaurantes.mesa')),
            ],
            options={
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.AddField(
            model_name='itemmesa',
            name='ocupacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='restaurantes.mesaocupacao'),
        ),
    ]
