# Generated by Django 6.1.1 on 2026-10-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0002_mesaocupacao_itemmesa_ocupacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesaocupacao',
            name='troco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mesaocupacao',
            name='valor_recebido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
