# Generated by Django 6.1.1 on 2026-09-17 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.cadastro', verbose_name='Favorecido'),
        ),
    ]
